### ISSUE TITLE
where is the umls_install.sh

### ISSUE THREAD

**Issue by JieyuZ2** [som-shahlab/trove#1]
Hi,

Just wondering where we could find the "umls_install.sh" script?

Thanks!

**Comment by Jatin6004** [comment]
Hi, 
Could you please help me in finding the "umls_install.sh" script?

Thanks

**Comment by jason-fries** [comment]
Hi @JieyuZ2 , @Jatin6004,

Sorry about the delay in responding! We've refactored the repo to include tooling making it easier to install the UMLS from source. Look for a refresh of `main` in the next day or so. This should fix you issues!
